<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SensorRecorderTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sensor_recorder')->insert([
            [
                'sensor_id' => 1,
                'recorder_id' => 1,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 1,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 1,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 1,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 1,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 2,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 2,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 2,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 2,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 2,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 3,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 3,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 3,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 3,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 3,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 4,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 4,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 4,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 4,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 4,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 5,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 5,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 5,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 5,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 5,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 6,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 6,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 6,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 6,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 6,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 7,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 7,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 7,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 7,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 7,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 8,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 8,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 8,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 8,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 8,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 9,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 9,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 9,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 9,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 9,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 10,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 10,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 10,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 10,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 10,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 11,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 11,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 11,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 11,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 11,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 12,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 12,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 12,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 12,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 12,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 13,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 13,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 13,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 13,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 13,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 14,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 14,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 14,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 14,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 14,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 15,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 15,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 15,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 15,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 15,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 16,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 16,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 16,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 16,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 16,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 17,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 17,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 17,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 17,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 17,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 18,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 18,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 18,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 18,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 18,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 19,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 19,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 19,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 19,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 19,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 20,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 20,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 20,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 20,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 20,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 21,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 21,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 21,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 21,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 21,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 22,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 22,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 22,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 22,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 22,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 1,
                'recorder_id' => 23,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 2,
                'recorder_id' => 23,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 3,
                'recorder_id' => 23,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 4,
                'recorder_id' => 23,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],
            [
                'sensor_id' => 5,
                'recorder_id' => 23,
                'created_at' => NOW(),
                'updated_at' => NOW(),
            ],

        ]);
    }
}
